version: '3'

networks:
  local:
    external: false
  vizgis:
    external: true

services:

  mariadb:
    image: mariadb:10.5
    env_file:
      - .env
    networks:
      - local
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:5-debian-10
    env_file:
      - .env
    networks:
      - local
      - vizgis
    volumes:
      - ${DATA_DIR}/wordpress:/bitnami/wordpress
      - ${DATA_DIR}/wordpress_nginx/wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro
      - ${DATA_DIR}/wordpress_nginx/nginx.conf:/opt/bitnami/wordpress/nginx.conf
    environment:
      - WORDPRESS_DATABASE_USER=${MYSQL_USER}
      - WORDPRESS_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${MYSQL_DATABASE}
    depends_on:
      - mariadb
    labels:
      - "traefik.http.routers.wordpress_vizgis.rule=Host(`vizgis.lt`)"
      - "traefik.http.routers.wordpress_vizgis.tls=true"
      - "traefik.docker.network=vizgis"
      - "traefik.http.services.wordpress_vizgis.loadbalancer.server.port=8080"
